name: 'Bitlab GitHub App Authentication'
description: 'Generate GitHub App token and configure Git authentication for Bitlab repositories'
author: 'Bitlab'

inputs:
  private-key:
    description: 'Bitlab GitHub App private key'
    required: true

outputs:
  token:
    description: 'Generated GitHub App token'
    value: ${{ steps.app-token.outputs.token }}

runs:
  using: 'composite'
  steps:
    - name: Generate GitHub App Token
      uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: 1592499
        private-key: ${{ inputs.private-key }}
        owner: Bitlabco

    - name: Configure Git Authentication
      shell: bash
      run: |
        git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/Bitlabco".insteadOf "ssh://git@github.com/Bitlabco"
        git config --global url."https://oauth2:${{ steps.app-token.outputs.token }}@github.com/Bitlabco".insteadOf "https://github.com/Bitlabco"